title = "Lucas Melin"
baseURL = "https://lucasmelin.com/"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Lucas Melin"
    author = "Lucas Melin"
    description = "Computer Engineering Student and QA Analyst in Ottawa, ON."
    logoBig = "/images/LucasMelin.jpg"
    logoSmall = "/images/LucasMelin.jpg"
    favicon = "favicon.ico"
    opengraphImage = "/images/LucasMelin.jpg"
    twitter = "sapping"
    linkedin = "melinlucas"
    github = "lucasmelin"
    email = "lucasmelin@gmail.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = false
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[permalinks]
    gallery = "/" # Redirect gallery index to home page

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4